apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: firefly

resources:
  - namespace.yaml
  - service-accounts.yaml
  - mariadb-config.yaml
  - mariadb.yaml
  - pvcs.yaml
  - deployment.yaml
  - httproute.yaml
