apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: firefly
  labels:
    app: mariadb
data:
  my.cnf: |
    [mysqld]
    max_connections = 100
    innodb_buffer_pool_size = 128M
    innodb_log_file_size = 48M
    innodb_flush_log_at_trx_commit = 2
    innodb_flush_method = O_DIRECT
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    skip-name-resolve

    [client]
    default-character-set = utf8mb4
